name: npm-install

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-node@v4
        with:
          node-version: 18.15.0
      - name: npm install and test 
        working-directory: ./baserepo/cypress
        run: |
          yarn
